# Generated by Django 5.2.1 on 2025-06-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер зала')], default='client', max_length=20),
        ),
    ]
