# Generated by Django 5.2.1 on 2025-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='places/')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('slot_duration', models.PositiveIntegerField(default=60, help_text='Slot duration in minutes')),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('gym', 'Тренажерный зал'), ('arena', 'Аренда спортивных площадок'), ('equipment', 'Аренда снаряжения'), ('poll', 'Бассейн'), ('sauna', 'Сайна'), ('other', 'Другое')], default='other', max_length=20)),
            ],
        ),
    ]
