# Generated by Django 5.2.1 on 2025-06-16 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_place_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
